### ISSUE TITLE
Need help to parse chainstate

### ISSUE THREAD

**Issue by amanusk** [sr-gi/bitcoin_tools#1]
Hi, and thanks for creating the tool. 
I am trying to run the example shown on the readme page to parse the UTXO database.   
Unfortunately, I was getting empty files as results. I was only able to get something in the file `utxos.txt` after changing `prefix=b'c'` to `prefix=b'C'` in this [line](https://github.com/sr-gi/bitcoin_tools/blob/0a9468eb5462dca7b5370a64e15ae37e86e04e10/bitcoin_tools/analysis/leveldb/utils.py#L284) in utils.py

After that, the file utxos.txt looks like this:
```
{"value": "81e14332003bf58224ccd41bd4c94bf0d4a711fc4e1187887c", "key": "4300000136ea56f3b0ee8fbb13059cbd4521ba38074fd9832a86f4335cd7d2267c00"}
{"value": "bf8d427b007ce9617e10685f9aa2f11d19272b0692c425bc83", "key": "43000007608f08c437696f0e12bc50927ac343e48c51f4b9c4a52a484998ad188902"}
{"value": "efd20680e52900df59f7cfb19c60b7e7d4087b15ca5612523d5c53", "key": "43000009c5d6812fe6fd011c921e566bc396d840293efc1c570777d95359fca78400"}
{"value": "d7ae4807016afa6ce4bcea3bfdb9cdcc1818fdf272e695854f", "key": "4300000b99fb3d107e8573bfad3d28b52087e6fb685b156777c73157fa452ba96000"}
{"value": "989160808027000b4d2d0c2252ede24fd76f0d242903d5758697b8", "key": "430000104fbfb34ef6c699cf1ec1f0f8e8da9c6bb71d81ca1c2e449529c86b815c00"}
```   
Does this make sense? 

When I later try to run `utxo_dump(f_utxos, f_parsed_utxos)` on this file, I get the error: 
```
Traceback (most recent call last):
  File "leveldb_dump.py", line 10, in <module>
    utxo_dump(f_utxos, f_parsed_utxos)
  File "/home/amanusk/Code/bitcoin_tools/bitcoin_tools/analysis/leveldb/data_dump.py", line 48, in utxo_dump
    utxo = decode_utxo(data["value"])
  File "/home/amanusk/Code/bitcoin_tools/bitcoin_tools/analysis/leveldb/utils.py", line 201, in decode_utxo
    data, offset = parse_b128(utxo, offset)
  File "/home/amanusk/Code/bitcoin_tools/bitcoin_tools/analysis/leveldb/utils.py", line 112, in parse_b128
    more_bytes = int(data, 16) & 0x80  # MSB b128 Varints have set the bit 128 for every byte but the last one,
ValueError: invalid literal for int() with base 16: ''
```
This happens even if I try to parse a single line of the file

I am running the latest version of bitcoin-core (Perhaps an older version is needed for the tools to work?). Is there anything special that needs to be done when starting bitcoind?  
Any help is appreciated.

**Comment by sr-gi** [comment]
The LevelDB structure was changed on v 0.15, so the parser won't work for the latest bitcoin-core version. I'm planning to update the parser soon, though.

**Comment by amanusk** [comment]
Got it. What is the last version you know to work?

**Comment by sr-gi** [comment]
Changes where made in 0.15, so any 0.14.x should work.

**Comment by sr-gi** [comment]
@amanusk Just letting you know that the decoder for 0.15 is now available in dev branch. It will be merged to main ASAP (during next week most likely).

**Comment by jhdscript** [comment]
how to install bitcoin 0.14x ?

**Comment by sr-gi** [comment]
@jhdscript You can find all the versions history at [bitcoin.org](https://bitcoin.org/en/version-history)

**Comment by jhdscript** [comment]
ok thanx i m trying it. I think my version doesn t work with nw chainstate format

**Comment by sr-gi** [comment]
The code in main branch only works versions 0.8-0.14 format. The code in dev branch include the parsers for both the 0.8-0.14 format and the new 0.15 one. However, we are redesigning some details on dev branch before merging it to master, so parts of the code may change.

**Comment by jhdscript** [comment]
arf i delete all my blocks from 8.15

Main branch works with 14.2 too ?

**Comment by sr-gi** [comment]
Sure, any 0.14x
