### ISSUE TITLE
Which linux distribution?

### ISSUE THREAD

**Issue by ubamnow404** [sr-gi/bitcoin_tools#10]
I've tried installing on a couple of distros (including my usual ubuntu environment and a reasonable-looking centos), but keep running into strange build/architecture issues.

An odd question maybe, but: which linux distribution are you using with this project? I'd like to tinker with the tools a bit, and it seems easier at this point to just use whatever OS you're using than work further on debugging the build/installation problems…

Thanks! :heart:

**Comment by sr-gi** [comment]
Should be fine with Ubuntu, we've tested it in Debian, Ubuntu and Arch, so it should run at least in those three. Feel free to post any build issues you may find (or refer both to FAQ and INSTALL for the most straightforward ones).

**Comment by ubamnow404** [comment]
I've not had luck yet. I get this error on every distro I've tried:

```
ImportError: /usr/lib/python2.7/site-packages/plyvel/_plyvel.so: undefined symbol: PyUnicodeUCS2_FromObject
```

It looks like others have had this problem with plyvel before too: https://github.com/wbolster/plyvel/issues/65

Any ideas for workarounds?

**Comment by wbolster** [comment]
see plyvel bug, will fix it shortly, use 0.9 in the mean time

**Comment by wbolster** [comment]
or use python 3 instead of legacy python 2.x.

**Comment by ubamnow404** [comment]
I appreciate you @wbolster

**Comment by sr-gi** [comment]
Thanks @wbolster!

I've been using 0.9 for a while, so never faced that issue @ubamnow404, I'd follow what @wbolster said and use v0.9 for the moment. (Using python 3 is not an option since all the library is coded in 2.x).

I'll leave the issue open just in case you face any other deploy issue. If not, feel free to close it.

**Comment by wbolster** [comment]
this should be solved now. see https://github.com/wbolster/plyvel/issues/65#issuecomment-357099428

**Comment by wbolster** [comment]
this issue can be closed

**Comment by ubamnow404** [comment]
:heart: yah, bitcoin_tools works now, thank you everyone :heart:
