### ISSUE TITLE
Don't work in python 3.6

### ISSUE THREAD

**Issue by 3Thiago** [sr-gi/bitcoin_tools#18]
This does not work in python 3.6, can it refresh?

**Comment by sr-gi** [comment]
The whole library is written in Python 2. We have no plans of updating to Python 3 in the short term, sorry.

**Comment by 3Thiago** [comment]
I tried using it in python 2.7 but I also have many errors. Which version of python is compatible?

**Comment by sr-gi** [comment]
It should work with Python 2.7.

Have you followed [INSTALL.md](https://github.com/sr-gi/bitcoin_tools/blob/master/INSTALL.md), [DEPENDENCIES.md](https://github.com/sr-gi/bitcoin_tools/blob/master/DEPENDENCIES.md) and [FAQ.md](https://github.com/sr-gi/bitcoin_tools/blob/master/FAQ.md)?

**Comment by sr-gi** [comment]
Any updates? Have you managed to make it work?

**Comment by 3Thiago** [comment]
Excuse me, I'm not going to use python 2. The other part of the project is all written in pyton 3.6 and has no way to go back to python 2
