### ISSUE TITLE
Not compatible with windows?

### ISSUE THREAD

**Issue by what-cloud** [sr-gi/bitcoin_tools#19]
ValueError: path 'C:\Users\Administrator/bitcoin_tools/' cannot end with '/'

  ----------------------------------------
  Failed building wheel for python-bitcoin-tools

**Comment by what-cloud** [comment]
pip install python-bitcoin-tools,

Win10, Python 3.6.2

**Comment by what-cloud** [comment]
will test again, thanks

**Comment by sr-gi** [comment]
Hey @what-cloud. The problem you're getting is because the config file is wrong. It's using '/' instead of '\', what it's the default in windows. It seems to be an error on the setup we uploaded to pypi. Have you tried building manually from source?
