### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by jhdscript** [sr-gi/bitcoin_tools#2]
Hello i m trying to use it on Windows but it seems donna work. Can you help? Thanx in advance. Regards

**Comment by sr-gi** [comment]
@jhdscript I have test it on Linux and Mac, not on Windows. If you post what's going wrong I can try to help you though.

**Comment by jhdscript** [comment]
Hello, and thanx for your fast reply. It seems one requirements doesnt work on Windows. See the screen.


![sans titre](https://user-images.githubusercontent.com/6814361/32468299-f99964cc-c34d-11e7-976c-04f4a8fd14d0.png)

Maybe could you help me. I only need to dump utxo like your sample to get addresses with balance. Regards

**Comment by jhdscript** [comment]
I already install Microsoft Visual C++ Compiler for Python 2.7

**Comment by sr-gi** [comment]
Is it still crashing after installing Visual C++ 9?

**Comment by jhdscript** [comment]
Yes :-(

**Comment by sr-gi** [comment]
Sorry, I hope I can help you better. I'll try to build it in a Windows system as soon as I can get my hands on one and have enough time. I may take a while though.

**Comment by jhdscript** [comment]
ok thanx

**Comment by sr-gi** [comment]
@jhdscript I've seen you commenting on the versions issue, have you managed to solve the windows building problem?

**Comment by jhdscript** [comment]
I installed an Ubuntu server with bitcoin 8.15 and i try thé main branche :/  so i delete all ans i reinstall 8.14.

I test After blockchain is downloaded . To use utxo script i need to stop bitcoind? How many time script take ?

**Comment by sr-gi** [comment]
Depends on the your system, and which parts of the code you are running. Parsing the whole chainstate can take about an hour on a laptop.

**Comment by agoora** [comment]
Compilation problem in Unbuntu 16.04  



Failed building wheel for plyvel
  Running setup.py clean for plyvel
Failed to build plyvel
Installing collected packages: plyvel, numpy, cycler, pytz, subprocess32, python-dateutil, backports.functools-lru-cache, pyparsing, matplotlib
  Running setup.py install for plyvel ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-YJZ_fL/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0ic4CF-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/plyvel
    copying plyvel/_version.py -> build/lib.linux-x86_64-2.7/plyvel
    copying plyvel/__init__.py -> build/lib.linux-x86_64-2.7/plyvel
    running build_ext
    building 'plyvel._plyvel' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/plyvel
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c plyvel/_plyvel.cpp -o build/temp.linux-x86_64-2.7/plyvel/_plyvel.o -Wall -g
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    plyvel/_plyvel.cpp:359:24: fatal error: leveldb/db.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-YJZ_fL/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0ic4CF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-YJZ_fL/plyvel/

**Comment by cpsola** [comment]
Please be sure to install all the [needed system dependencies](https://github.com/sr-gi/bitcoin_tools/tree/dev#dependencies):

For instance, for Debian/Ubuntu based systems, `python-tk` and `libleveldb-dev` must be installed:
```
sudo apt-get install python-tk libleveldb-dev
```

**Comment by agoora** [comment]
OK,thanks.
