### ISSUE TITLE
Error in get_chainstate_lastblock / deobfuscate_value

### ISSUE THREAD

**Issue by Karl483r** [sr-gi/bitcoin_tools#20]
Hi,

getting the last block from the chainstate fails for several chainstate heights. One example is height 176760 with the block hash 0000000000000a9569c34dd2f69d39b9763706991418b6ea3836c2b66fb57700. get_chainstate_lastblock calls deobfuscate_value where the [check](https://github.com/sr-gi/bitcoin_tools/blob/master/bitcoin_tools/analysis/status/utils.py#L872) "assert len(value) == len(r)" fails. 

I think the [if statement](https://github.com/sr-gi/bitcoin_tools/blob/master/bitcoin_tools/analysis/status/utils.py#L869) above this check is wrong, as an arbitary number of leading zeros could be dropped and not only one. 

Steps to replicate this issue:

1. Start bitcoind and synchronize blockchain until at least block 176760
2. Revert bitcoind to block 176760 by issuing `bitcoin-cli  invalidateblock 0000000000000056c50dbea31d9ad6f429aaad61ca313e72e4c00b53fd9fb3fb` (invalidate block 176761)
3. Stop bitcoind and call get_chainstate_lastblock on the current chainstate

PS: Thanks a lot for the bitcoin tools, they helped me a lot!

**Comment by sr-gi** [comment]
I think you're right.

https://github.com/sr-gi/bitcoin_tools/blob/master/bitcoin_tools/analysis/status/utils.py#L866-L874

That whole chuck could be removed and zfill could be run after formatting tho ensure the resulting value has the correct length.

```
    r = format(int(value, 16) ^ int(extended_key, 16), 'x').zfill(l_value)

    return r
```

Could you try the hotfix? I don't have a setup handy atm.

**Comment by Karl483r** [comment]
Yes that solves this issue.

Thank you!
