### ISSUE TITLE
utxo types

### ISSUE THREAD

**Issue by diamondduck** [sr-gi/bitcoin_tools#3]
I was looking at utxo_dump function. I am trying to understand the utxo database. 
Can you specify the 6 standard utxo types ?
`# Standard UTXO types
    std_types = [0, 1, 2, 3, 4, 5]` 

I thought there are only like 4-5 of them ? P2PKH, P2PK, P2MS, P2SH ? 
also, based on the output, is it correct that:
```
0 --> P2PKH
1 --> P2PK
2 --> P2SH
```
how about 3,4,5 ? 
Thanks

**Comment by sr-gi** [comment]
You can find it commented [here](https://github.com/sr-gi/bitcoin_tools/blob/cf5c544313be74e01d6d1385a2867cc9f05196d5/bitcoin_tools/analysis/status/utils.py#L353-L357). 

Basically:

```
0 --> P2PKH
1 --> P2SH
2-3 --> P2PK (Compressed keys)
4-5 --> P2PK (Uncompressed keys)
```

The matching source code from the Bitcoin Core can be found [here](https://github.com/bitcoin/bitcoin/blob/4afb5aa9e173991548be3627c6df258368d95ff3/src/compressor.cpp#L88-L131).

**Comment by diamondduck** [comment]
thanks
