### ISSUE TITLE
How can dump all hash160, and address with unspent balances?

### ISSUE THREAD

**Issue by agoora** [sr-gi/bitcoin_tools#5]
Please help me !

**Comment by agoora** [comment]
Hi Sergi,
Can you help me please ...
How can I dump all hash160, and address with unspent balances?
Thank you.

**Comment by sr-gi** [comment]
Are you under master or dev branch? Which version of the core you are running?

**Comment by agoora** [comment]
I'm not under master or dev branch...
I just want to make statistics and detailed correlations with this data.
I use core Bitcoin Core version 0.14.2.
Please let me know if your tool can dump all hash160, and address with unspent balances?

Thanks again.

**Comment by sr-gi** [comment]
Yes, it can. You may have to parse the LevelDB by calling `parse_ldb` under `/bitcoin_tools/analysis/status/utils.py`in `dev` branch. (Notice that you may specify that the version you are using is under 0.15 or the resulting file will be empty).

Then you need to dump all the `utxo` data by calling `utxo_dump`. That will give you all the data from the `chainstate` porperly decoded. You can find the `hash160` of `P2PKH` and `P2SH` `utxos` under the field `data` under `outs` for `out_types` `0` and `1` respectively. (Other `out_types` encode `P2PKH` and non-std outputs).

Notice also that you won't find `bitcoin addresses` in the `utxo set`, only `hash160`. If you want to get the corresponding  `bitcoin address` for a given `hash160` you can use `hash_160_to_btc_address` under `bitcoin_tools/wallet.py`.

**Comment by agoora** [comment]
Thank you for your answer.

Can you please list all python commands, I do not really understand how to proceed step by step.

Thank you very much for you help and your time !
Marc.

**Comment by agoora** [comment]
Thank you for your answer.
Can you please list all python commands, I do not really understand how to proceed step by step.
Thank you very much for you help and your time !

**Comment by agoora** [comment]
Please help me with commands to dump hash160 with associated adress.

**Comment by levduc** [comment]
you may want to look into `parse_ldb` in `status/ultis` and `utxo_dump` in `status/data_dump`. After getting the utxo file, you can write your own code to find all utxo related to that address.

**Comment by sr-gi** [comment]
You have an example of how to do most of it in the README.md.

If you have properly installed and configured the library (installed all the dependences depending on your OS and also the Python ones). You can do:

1. Swith branch to `dev`:

From terminal type git checkout dev

2. Parse the `chainstate`:

```
version = 0.14.2
f_utxos = "decoded_utxos.json"
f_parsed_utxos = "parsed_utxos.json"

parse_ldb(f_utxos, fin_name=chainstate, version=version)
utxo_dump(f_utxos, f_parsed_utxos, version=version)
```

3. Write your own code for the purpose you aim:

Once you have the `parsed_utxos.json` file, you will need to read it line by line and get all the `utxos` of type `0` (the ones that correspond to `P2PKH`), under the field `outs["out_type"]` of the dictionary.

Then, for every `utxo` of type `0`, just apply the function `hash_160_to_btc_address` that you can import from `/bitcoin_tools/utils.py` ([here](https://github.com/sr-gi/bitcoin_tools/blob/dev/bitcoin_tools/utils.py))

If you have any specific trouble with some function let me know (they are quite exhaustively commented and explain in the docstrings, but still, don't hesitate), but don't ask me to code it for you.

**Comment by agoora** [comment]
I have this message :

test@ubuntu:/usr/lib/python2.7/bitcoin_tools$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitcoin_tools.core.keys import generate_keys, store_keys
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/bitcoin_tools/__init__.py", line 4, in <module>
    raise Exception("You don't have a configuration file. Make a copy of sample_conf.py")
Exception: You don't have a configuration file. Make a copy of sample_conf.py
>>>

**Comment by agoora** [comment]
From 3 days I'm trying to configure the "conf.py" file, please help me with a simple solution .....
Thanks Sergi.

**Comment by sr-gi** [comment]
First you had no conf.py file at all, the Exception was telling you to create one using sample_conf.py as example. For what I see here, it looks like your paths are not strings, notice that all  the paths should be surrounded by `"` as the examples provided.

**Comment by agoora** [comment]
This is my "conf.py" files in Ubuntu 17.10 :
Where is the problem, .....please post a completed mode !

home_dir = "/home/bf/"  # Home dir (e.g: "/home/your_user_name/").
btc_core_path = "/home/test/.bitcoin/"  # Path to Bitcoin core (usually home_dir + ".bitcoin/").
bitcoin_tools_dir = "/home/test/bitcoin_tools"  # Bitcoin_tools data dir. (NOT GIT CODE) (usually home_dir + "bitcoin_tools")
address_vault = "/home/test/bitcoin_tool bitcoin_addresses/"  # Address vault (where keys are stored) (e.g: bitcoin_tools_dir + "bitcoin_addresses/").
data_path = "/home/test/bitcoin_tool/data/"  # # Data storage path (for IO) (e.g: bitcoin_tools_dir + "data/").
figs_path = "/home/test/bitcoin_tool/figs/"  # Generated figures storage path (e.g: bitcoin_tools_dir + "figs/").

**Comment by agoora** [comment]
Please help me to solve this problem !

**Comment by sr-gi** [comment]
The file seems good, but as I told you in the other issue you write on, it looks like you are not in the proper git branch, checkout first and try to run the code.

**Comment by agoora** [comment]
I m in the git branch "dev" I have executed git checkout dev !

**Comment by sr-gi** [comment]
Can you post the result of `git branch` and the error you are getting when executing the code?

**Comment by agoora** [comment]
test@bf:~/bitcoin_tools$ git branch
* dev
  master

**Comment by sr-gi** [comment]
And the error?

**Comment by agoora** [comment]
None, just what I sent ...

**Comment by sr-gi** [comment]
Then, what's the problem?

**Comment by agoora** [comment]
test@bf:~/bitcoin_tools$ git branch
* dev
  master
test@bf:~/bitcoin_tools$

**Comment by agoora** [comment]
test@bf:~/bitcoin_tools/bitcoin_tools$ python dev.py
Traceback (most recent call last):
  File "dev.py", line 1, in <module>
    from bitcoin_tools.analysis.status.data_dump import utxo_dump
ImportError: No module named bitcoin_tools.analysis.status.data_dump
test@bf:~/bitcoin_tools/bitcoin_tools$

**Comment by agoora** [comment]
????

**Comment by agoora** [comment]
what does not run correctly?

**Comment by sr-gi** [comment]
Have you included bitcoin_tools as part of your `PYTHONPATH` or stored the library under `/usr/lib/pyton2.7`?

**Comment by agoora** [comment]
How can I do, probably not ....

**Comment by sr-gi** [comment]
Check the [installation section](https://github.com/sr-gi/bitcoin_tools/tree/dev#installation) at the README on dev.

**Comment by agoora** [comment]
How the folder "bitcoin_tools"  is included in another "bitcoin_tools" folder ...

What is the correct parameter? :
"/home/bf/bitcoin_tools/bitcoin_tools"
"/home/bf/bitcoin_tools"

**Comment by sr-gi** [comment]
The internal bitcoin_tools is the name of the python library, while the external is the name of the git repository. You should include the external one:

`"/home/bf/bitcoin_tools"`

**Comment by agoora** [comment]
yes ....
1. I places lib folder "bitcoin_tools/bitcoin_tools"  in /usr/lib/python2.7/

ok?

**Comment by agoora** [comment]
OR "bitcoin_tools" in /usr/lib/python2.7/

**Comment by sr-gi** [comment]
bitcoin_tools/bitcoin_tools in /usr/lib/python2.7/

**Comment by agoora** [comment]
OK ...

**Comment by agoora** [comment]
Something goes ... thank you very much.

**Comment by sr-gi** [comment]
Cool, I close the issue then. Next time be more patient, I always respond to the issues, so not push it.

**Comment by agoora** [comment]
Ok, thanks again.
