### ISSUE TITLE
Litecoin

### ISSUE THREAD

**Issue by jhdscript** [sr-gi/bitcoin_tools#6]
Donyou know if it s possible to use the tool to extract addresses from litecoin core?

**Comment by sr-gi** [comment]
Never tried with Litecoin, I'm not sure if the use the exact same encoding for their chainstate, but it may be possible. Nor even if the prefixes for the key entries are the same. 

If they are not, it may be easy to slightly change the code to make it work, as long as they use a similar one.

If you try and you have any trouble let me know and we can try to solve it together.

**Comment by sr-gi** [comment]
For future travelers, we've tested STATUS within Litecoin and it works, so you may be able to use it either.
