### ISSUE TITLE
is it possible to get all bitcoin addresses having balance ?

### ISSUE THREAD

**Issue by rawmaterials** [sr-gi/bitcoin_tools#9]
using this repo ?

Thanks

**Comment by sr-gi** [comment]
Yes, you would need to query the `utxo set` using `STATUS`, and for every output you find in the set analyze the `type` and `script`. Check [here](https://github.com/sr-gi/bitcoin_tools/blob/master/bitcoin_tools/analysis/status/utils.py#L353-L357) for more information about each type.

You won't find all the balances aggregated by addresses, so you should do it yourself, but it should be too complex.

**Comment by sr-gi** [comment]
I'll close the issue if you don't have any other question regarding this. Let me know otherwise.

**Comment by rawmaterials** [comment]
yes, i have managed to get utxo set by using rusty blockparser., this issue can be closed.,

thanks.
